version: "2"

services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
    php:
        image: php-redis
        volumes:
            - ./code:/code
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - /data/redis:/data
        command: redis-server --appendonly yes